### PR TITLE
minimal update to get it working for julia-0.6

### PR DESCRIPTION
**Pull request by freeboson**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
any chance of fixing tests?

**Comment by freeboson** [comment]
Yeah, I'll get back to it in a few days. I guess REQUIRES needs to be
added/fixed.

I just wanted to see if it would be faster than JSON.jl for my datasets but
the performance was about the same.

**Comment by samuelcolvin** [comment]
Ye, my suspicion is that julia's own JSON package will be much faster than when I last checked.

https://gist.github.com/samuelcolvin/11101522

**Comment by freeboson** [comment]
@samuelcolvin OK the tests are working now

**Comment by samuelcolvin** [comment]
Looks good. Thank you.

I haven't done any work with julia for some time, do I need to do anything more to make it usable for you?

**Comment by freeboson** [comment]
I came across this project via https://github.com/JuliaIO/JSON.jl/issues/59 and just wanted to see if the performance was improved here. `JSON.jl` is giving about 2x slower performance compared to `stdlib` `json` in CPython for my use case. `uJSON.jl` is similar at the moment, but perhaps it is faster in other cases.

**Comment by xgdgsc** [comment]
I tested here `JSON.jl` is faster than `uJSON.jl` now, but not even close to json from Python. Any ideas on directions to fix this?

**Comment by samuelcolvin** [comment]
Long time ago since I looked in to this, but I seem to remember in julia 0.3,0.4 (?) dictionaries and hashing in particular weren't as well optimised as python.

If that's true, and since it's a fundamental language feature there's not much that can be done in `JSON.jl` or `uJSON.jl`.

**Pull request merged**
